# Keys for LocalizationManger to use in source code: MIT License
# @author Vladimir Petrenko
tool
class_name LocalizationKeys

const KEY_NAME = "KEY_NAME"
const KEY_PLAY = "KEY_PLAY"
const KEY_SETTINGS = "KEY_SETTINGS"
const KEY_LANGUAGE = "KEY_LANGUAGE"
const KEY_LANGUAGESELECT = "KEY_LANGUAGESELECT"
const KEY_BACK = "KEY_BACK"
const KEY_QUIT = "KEY_QUIT"
const KEY_TEXT = "KEY_TEXT"
const KEY_PLAY_VIDEO = "KEY_PLAY_VIDEO"
const KEY_PLACEHOLDER = "KEY_PLACEHOLDER"
const KEY_VALUE = "KEY_VALUE"
const KEY_APPLY = "KEY_APPLY"
const KEY_PLACEHOLDER_NAME = "KEY_PLACEHOLDER_NAME"
const KEY_PLACEHOLDER_AGE = "KEY_PLACEHOLDER_AGE"
const KEY_PLACEHOLDER_NAME_AGE = "KEY_PLACEHOLDER_NAME_AGE"

const KEYS = [
 "KEY_NAME",
 "KEY_PLAY",
 "KEY_SETTINGS",
 "KEY_LANGUAGE",
 "KEY_LANGUAGESELECT",
 "KEY_BACK",
 "KEY_QUIT",
 "KEY_TEXT",
 "KEY_PLAY_VIDEO",
 "KEY_PLACEHOLDER",
 "KEY_VALUE",
 "KEY_APPLY",
 "KEY_PLACEHOLDER_NAME",
 "KEY_PLACEHOLDER_AGE",
 "KEY_PLACEHOLDER_NAME_AGE"
]